*
* file generated by qgraf-3.4.2
*
*  output= 'all3vertx.h' ;
*  style= 'arraytree.sty' ;
*  model= ' weakP1';
*  in = b;
*  out= u, ubar, s, photon;
*  loops= 0;
*  loop_momentum= ;
*  options= ;
*
 
Local D1tree= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),u(-4,-q2),ubar(-2,-q1),b(1,p1-q4));
 
Local D2tree= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(u(1,q1+q4))*
 vrtx(ubar(-2,-q1),u(1,q1+q4),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),u(-4,-q2),ubar(2,-q1-q4),b(-1,p1));
 
Local D3tree= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(u(1,-q2-q4))*
 vrtx(ubar(2,q2+q4),u(-4,-q2),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),u(1,-q2-q4),ubar(-2,-q1),b(-1,p1));
 
Local D4tree= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(sbar(2,-q3-q4),u(-4,-q2),ubar(-2,-q1),b(-1,p1));
 
Local D1treeC= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),u(-4,-q2),ubar(-2,-q1),b(1,p1-q4));
 
Local D2treeC= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(u(1,q1+q4))*
 vrtx(ubar(-2,-q1),u(1,q1+q4),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),u(-4,-q2),ubar(2,-q1-q4),b(-1,p1));
 
Local D3treeC= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(u(1,-q2-q4))*
 vrtx(ubar(2,q2+q4),u(-4,-q2),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),u(1,-q2-q4),ubar(-2,-q1),b(-1,p1));
 
Local D4treeC= (-1)*
 pol(b(-1,p1))*
 pol(u(-2,q1))*
 pol(ubar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(sbar(2,-q3-q4),u(-4,-q2),ubar(-2,-q1),b(-1,p1));

* end

