*
* file generated by qgraf-3.4.2
*
*  output= 'all3vertx.h' ;
*  style= 'arraytree.sty' ;
*  model= ' weakP1';
*  in = u, U, s, photon;
*  out= b;
*  loops= 0;
*  loop_momentum= ;
*  options= ;
*
 
Local D1tree= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(u(1,p1+p4))*
 vrtx(ubar(2,-p1-p4),u(-1,p1),photon(-7,p4))*
 vrtx(ubar(-3,p2),u(1,p1+p4),bbar(-2,-q1),s(-5,p3));
 
Local D2tree= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(u(1,-p2-p4))*
 vrtx(ubar(-3,p2),u(1,-p2-p4),photon(-7,p4))*
 vrtx(ubar(2,p2+p4),u(-1,p1),bbar(-2,-q1),s(-5,p3));
 
Local D3tree= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(s(1,p3+p4))*
 vrtx(sbar(2,-p3-p4),s(-5,p3),photon(-7,p4))*
 vrtx(ubar(-3,p2),u(-1,p1),bbar(-2,-q1),s(1,p3+p4));
 
Local D4tree= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(b(1,-p4+q1))*
 vrtx(bbar(-2,-q1),b(1,-p4+q1),photon(-7,p4))*
 vrtx(ubar(-3,p2),u(-1,p1),bbar(2,p4-q1),s(-5,p3));
 
Local D1treeC= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(u(1,p1+p4))*
 vrtx(ubar(2,-p1-p4),u(-1,p1),photon(-7,p4))*
 vrtx(ubar(-3,p2),u(1,p1+p4),bbar(-2,-q1),s(-5,p3));
 
Local D2treeC= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(u(1,-p2-p4))*
 vrtx(ubar(-3,p2),u(1,-p2-p4),photon(-7,p4))*
 vrtx(ubar(2,p2+p4),u(-1,p1),bbar(-2,-q1),s(-5,p3));
 
Local D3treeC= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(s(1,p3+p4))*
 vrtx(sbar(2,-p3-p4),s(-5,p3),photon(-7,p4))*
 vrtx(ubar(-3,p2),u(-1,p1),bbar(-2,-q1),s(1,p3+p4));
 
Local D4treeC= (+1)*
 pol(u(-1,p1))*
 pol(ubar(-3,p2))*
 pol(s(-5,p3))*
 pol(photon(-7,p4))*
 pol(b(-2,q1))*
 prop(b(1,-p4+q1))*
 vrtx(bbar(-2,-q1),b(1,-p4+q1),photon(-7,p4))*
 vrtx(ubar(-3,p2),u(-1,p1),bbar(2,p4-q1),s(-5,p3)); 

* end

