*
* file generated by qgraf-3.4.2
*
*  output= 'Diagrams1lSS.h' ;
*  style= 'array1l.sty' ;
*  model= 'WeakHPingSS';
*  in = b;
*  out= s, sbar, s, photon;
*  loops= 1;
*  loop_momentum= k;
*  options= notadpole, onshell;
*  true = iprop[photon,0,0];
*  true = chord[g,1,1] ;
*
 
Local D1OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(b(3,-k1+p1-q4))*
 prop(g(5,-k1))*
 prop(b(7,p1-q4))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(bbar(4,k1-p1+q4),b(1,p1-q4),g(5,-k1))*
 vrtx(bbar(8,-p1+q4),b(3,-k1+p1-q4),g(6,k1))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(-6,-q3),b(7,p1-q4));
 
Local D2OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(s(3,k1+q1+q4))*
 prop(g(5,-k1))*
 prop(s(7,q1+q4))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(sbar(2,-q1-q4),s(3,k1+q1+q4),g(5,-k1))*
 vrtx(sbar(4,-k1-q1-q4),s(7,q1+q4),g(6,k1))*
 vrtx(sbar(-6,-q3),s(-4,-q2),sbar(8,-q1-q4),b(-1,p1));
 
Local D3OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(s(3,-k1-q2-q4))*
 prop(g(5,-k1))*
 prop(s(7,-q2-q4))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(sbar(4,k1+q2+q4),s(1,-q2-q4),g(5,-k1))*
 vrtx(sbar(8,q2+q4),s(3,-k1-q2-q4),g(6,k1))*
 vrtx(sbar(-2,-q1),s(7,-q2-q4),sbar(-6,-q3),b(-1,p1));
 
Local D4OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(s(3,k1+q3+q4))*
 prop(g(5,-k1))*
 prop(s(7,q3+q4))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(sbar(2,-q3-q4),s(3,k1+q3+q4),g(5,-k1))*
 vrtx(sbar(4,-k1-q3-q4),s(7,q3+q4),g(6,k1))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(8,-q3-q4),b(-1,p1));
 
Local D5OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,k1))*
 prop(g(3,k1-p1))*
 prop(b(5,k1-q4))*
 prop(b(7,p1-q4))*
 vrtx(bbar(2,-k1),b(-1,p1),g(3,k1-p1))*
 vrtx(bbar(6,-k1+q4),b(1,k1),photon(-8,-q4))*
 vrtx(bbar(8,-p1+q4),b(5,k1-q4),g(4,-k1+p1))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(-6,-q3),b(7,p1-q4));
 
Local D6OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-k1))*
 prop(g(3,k1+q1))*
 prop(s(5,-k1+q4))*
 prop(s(7,q1+q4))*
 vrtx(sbar(-2,-q1),s(1,-k1),g(3,k1+q1))*
 vrtx(sbar(2,k1),s(5,-k1+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1-q4),s(7,q1+q4),g(4,-k1-q1))*
 vrtx(sbar(-6,-q3),s(-4,-q2),sbar(8,-q1-q4),b(-1,p1));
 
Local D7OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,k1))*
 prop(g(3,k1+q2))*
 prop(s(5,k1-q4))*
 prop(s(7,-q2-q4))*
 vrtx(sbar(2,-k1),s(-4,-q2),g(3,k1+q2))*
 vrtx(sbar(6,-k1+q4),s(1,k1),photon(-8,-q4))*
 vrtx(sbar(8,q2+q4),s(5,k1-q4),g(4,-k1-q2))*
 vrtx(sbar(-2,-q1),s(7,-q2-q4),sbar(-6,-q3),b(-1,p1));
 
Local D8OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-k1))*
 prop(g(3,k1+q3))*
 prop(s(5,-k1+q4))*
 prop(s(7,q3+q4))*
 vrtx(sbar(-6,-q3),s(1,-k1),g(3,k1+q3))*
 vrtx(sbar(2,k1),s(5,-k1+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1-q4),s(7,q3+q4),g(4,-k1-q3))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(8,-q3-q4),b(-1,p1));
 
Local D9OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(b(7,k1+p1-q4))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(bbar(8,-k1-p1+q4),b(1,p1-q4),g(4,k1))*
 vrtx(sbar(-6,-q3),s(-4,-q2),sbar(6,-k1-q1),b(7,k1+p1-q4));
 
Local D10OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(g(3,-k1))*
 prop(s(5,-k1-q2))*
 prop(b(7,k1+p1-q4))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(6,k1+q2),s(-4,-q2),g(3,-k1))*
 vrtx(bbar(8,-k1-p1+q4),b(1,p1-q4),g(4,k1))*
 vrtx(sbar(-2,-q1),s(5,-k1-q2),sbar(-6,-q3),b(7,k1+p1-q4));
 
Local D11OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q3))*
 prop(b(7,k1+p1-q4))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(5,k1+q3),g(3,-k1))*
 vrtx(bbar(8,-k1-p1+q4),b(1,p1-q4),g(4,k1))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(6,-k1-q3),b(7,k1+p1-q4));
 
Local D12OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,-k1+q1+q4))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(2,-q1-q4),s(7,-k1+q1+q4),g(4,k1))*
 vrtx(sbar(-6,-q3),s(-4,-q2),sbar(8,k1-q1-q4),b(5,-k1+p1));
 
Local D13OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(g(3,-k1))*
 prop(s(5,-k1-q2))*
 prop(s(7,-k1+q1+q4))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1+q2),s(-4,-q2),g(3,-k1))*
 vrtx(sbar(2,-q1-q4),s(7,-k1+q1+q4),g(4,k1))*
 vrtx(sbar(-6,-q3),s(5,-k1-q2),sbar(8,k1-q1-q4),b(-1,p1));
 
Local D14OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q3))*
 prop(s(7,-k1+q1+q4))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(5,k1+q3),g(3,-k1))*
 vrtx(sbar(2,-q1-q4),s(7,-k1+q1+q4),g(4,k1))*
 vrtx(sbar(6,-k1-q3),s(-4,-q2),sbar(8,k1-q1-q4),b(-1,p1));
 
Local D15OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,k1-q2-q4))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(8,-k1+q2+q4),s(1,-q2-q4),g(4,k1))*
 vrtx(sbar(-2,-q1),s(7,k1-q2-q4),sbar(-6,-q3),b(5,-k1+p1));
 
Local D16OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(s(7,k1-q2-q4))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(sbar(8,-k1+q2+q4),s(1,-q2-q4),g(4,k1))*
 vrtx(sbar(-6,-q3),s(7,k1-q2-q4),sbar(6,-k1-q1),b(-1,p1));
 
Local D17OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q3))*
 prop(s(7,k1-q2-q4))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(5,k1+q3),g(3,-k1))*
 vrtx(sbar(8,-k1+q2+q4),s(1,-q2-q4),g(4,k1))*
 vrtx(sbar(-2,-q1),s(7,k1-q2-q4),sbar(6,-k1-q3),b(-1,p1));
 
Local D18OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,-k1+q3+q4))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(2,-q3-q4),s(7,-k1+q3+q4),g(4,k1))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(8,k1-q3-q4),b(5,-k1+p1));
 
Local D19OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(s(7,-k1+q3+q4))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(sbar(2,-q3-q4),s(7,-k1+q3+q4),g(4,k1))*
 vrtx(sbar(6,-k1-q1),s(-4,-q2),sbar(8,k1-q3-q4),b(-1,p1));
 
Local D20OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(g(3,-k1))*
 prop(s(5,-k1-q2))*
 prop(s(7,-k1+q3+q4))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1+q2),s(-4,-q2),g(3,-k1))*
 vrtx(sbar(2,-q3-q4),s(7,-k1+q3+q4),g(4,k1))*
 vrtx(sbar(-2,-q1),s(5,-k1-q2),sbar(8,k1-q3-q4),b(-1,p1));
 
Local D21OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(b(3,-k1+p1))*
 prop(s(5,-k1+q1))*
 prop(b(7,-k1+p1-q4))*
 vrtx(bbar(4,k1-p1),b(-1,p1),g(1,-k1))*
 vrtx(sbar(-2,-q1),s(5,-k1+q1),g(2,k1))*
 vrtx(bbar(8,k1-p1+q4),b(3,-k1+p1),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(-4,-q2),sbar(6,k1-q1),b(7,-k1+p1-q4));
 
Local D22OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(b(3,-k1+p1))*
 prop(s(5,k1-q2))*
 prop(b(7,-k1+p1-q4))*
 vrtx(bbar(4,k1-p1),b(-1,p1),g(1,-k1))*
 vrtx(sbar(6,-k1+q2),s(-4,-q2),g(2,k1))*
 vrtx(bbar(8,k1-p1+q4),b(3,-k1+p1),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1-q2),sbar(-6,-q3),b(7,-k1+p1-q4));
 
Local D23OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(b(3,-k1+p1))*
 prop(s(5,-k1+q3))*
 prop(b(7,-k1+p1-q4))*
 vrtx(bbar(4,k1-p1),b(-1,p1),g(1,-k1))*
 vrtx(sbar(-6,-q3),s(5,-k1+q3),g(2,k1))*
 vrtx(bbar(8,k1-p1+q4),b(3,-k1+p1),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(6,k1-q3),b(7,-k1+p1-q4));
 
Local D24OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,k1+q1))*
 prop(b(5,k1+p1))*
 prop(s(7,k1+q1+q4))*
 vrtx(sbar(-2,-q1),s(3,k1+q1),g(1,-k1))*
 vrtx(bbar(6,-k1-p1),b(-1,p1),g(2,k1))*
 vrtx(sbar(4,-k1-q1),s(7,k1+q1+q4),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(-4,-q2),sbar(8,-k1-q1-q4),b(5,k1+p1));
 
Local D25OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,k1+q1))*
 prop(s(5,k1-q2))*
 prop(s(7,k1+q1+q4))*
 vrtx(sbar(-2,-q1),s(3,k1+q1),g(1,-k1))*
 vrtx(sbar(6,-k1+q2),s(-4,-q2),g(2,k1))*
 vrtx(sbar(4,-k1-q1),s(7,k1+q1+q4),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(5,k1-q2),sbar(8,-k1-q1-q4),b(-1,p1));
 
Local D26OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,k1+q1))*
 prop(s(5,-k1+q3))*
 prop(s(7,k1+q1+q4))*
 vrtx(sbar(-2,-q1),s(3,k1+q1),g(1,-k1))*
 vrtx(sbar(-6,-q3),s(5,-k1+q3),g(2,k1))*
 vrtx(sbar(4,-k1-q1),s(7,k1+q1+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1-q3),s(-4,-q2),sbar(8,-k1-q1-q4),b(-1,p1));
 
Local D27OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,-k1-q2))*
 prop(b(5,k1+p1))*
 prop(s(7,-k1-q2-q4))*
 vrtx(sbar(4,k1+q2),s(-4,-q2),g(1,-k1))*
 vrtx(bbar(6,-k1-p1),b(-1,p1),g(2,k1))*
 vrtx(sbar(8,k1+q2+q4),s(3,-k1-q2),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(7,-k1-q2-q4),sbar(-6,-q3),b(5,k1+p1));
 
Local D28OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,-k1-q2))*
 prop(s(5,-k1+q1))*
 prop(s(7,-k1-q2-q4))*
 vrtx(sbar(4,k1+q2),s(-4,-q2),g(1,-k1))*
 vrtx(sbar(-2,-q1),s(5,-k1+q1),g(2,k1))*
 vrtx(sbar(8,k1+q2+q4),s(3,-k1-q2),photon(-8,-q4))*
 vrtx(sbar(-6,-q3),s(7,-k1-q2-q4),sbar(6,k1-q1),b(-1,p1));
 
Local D29OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,-k1-q2))*
 prop(s(5,-k1+q3))*
 prop(s(7,-k1-q2-q4))*
 vrtx(sbar(4,k1+q2),s(-4,-q2),g(1,-k1))*
 vrtx(sbar(-6,-q3),s(5,-k1+q3),g(2,k1))*
 vrtx(sbar(8,k1+q2+q4),s(3,-k1-q2),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(7,-k1-q2-q4),sbar(6,k1-q3),b(-1,p1));
 
Local D30OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,k1+q3))*
 prop(b(5,k1+p1))*
 prop(s(7,k1+q3+q4))*
 vrtx(sbar(-6,-q3),s(3,k1+q3),g(1,-k1))*
 vrtx(bbar(6,-k1-p1),b(-1,p1),g(2,k1))*
 vrtx(sbar(4,-k1-q3),s(7,k1+q3+q4),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(-4,-q2),sbar(8,-k1-q3-q4),b(5,k1+p1));
 
Local D31OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,k1+q3))*
 prop(s(5,-k1+q1))*
 prop(s(7,k1+q3+q4))*
 vrtx(sbar(-6,-q3),s(3,k1+q3),g(1,-k1))*
 vrtx(sbar(-2,-q1),s(5,-k1+q1),g(2,k1))*
 vrtx(sbar(4,-k1-q3),s(7,k1+q3+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1-q1),s(-4,-q2),sbar(8,-k1-q3-q4),b(-1,p1));
 
Local D32OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(g(1,-k1))*
 prop(s(3,k1+q3))*
 prop(s(5,k1-q2))*
 prop(s(7,k1+q3+q4))*
 vrtx(sbar(-6,-q3),s(3,k1+q3),g(1,-k1))*
 vrtx(sbar(6,-k1+q2),s(-4,-q2),g(2,k1))*
 vrtx(sbar(4,-k1-q3),s(7,k1+q3+q4),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1-q2),sbar(8,-k1-q3-q4),b(-1,p1));
 
Local D33OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(s(7,k1-q2))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(sbar(8,-k1+q2),s(-4,-q2),g(4,k1))*
 vrtx(sbar(-6,-q3),s(7,k1-q2),sbar(6,-k1-q1),b(1,p1-q4));
 
Local D34OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(s(7,-k1+q3))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(sbar(-6,-q3),s(7,-k1+q3),g(4,k1))*
 vrtx(sbar(6,-k1-q1),s(-4,-q2),sbar(8,k1-q3),b(1,p1-q4));
 
Local D35OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(b(1,p1-q4))*
 prop(g(3,-k1))*
 prop(s(5,-k1-q2))*
 prop(s(7,-k1+q3))*
 vrtx(bbar(2,-p1+q4),b(-1,p1),photon(-8,-q4))*
 vrtx(sbar(6,k1+q2),s(-4,-q2),g(3,-k1))*
 vrtx(sbar(-6,-q3),s(7,-k1+q3),g(4,k1))*
 vrtx(sbar(-2,-q1),s(5,-k1-q2),sbar(8,k1-q3),b(1,p1-q4));
 
Local D36OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,k1-q2))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(8,-k1+q2),s(-4,-q2),g(4,k1))*
 vrtx(sbar(-6,-q3),s(7,k1-q2),sbar(2,-q1-q4),b(5,-k1+p1));
 
Local D37OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,-k1+q3))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(-6,-q3),s(7,-k1+q3),g(4,k1))*
 vrtx(sbar(2,-q1-q4),s(-4,-q2),sbar(8,k1-q3),b(5,-k1+p1));
 
Local D38OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q1+q4))*
 prop(g(3,-k1))*
 prop(s(5,-k1-q2))*
 prop(s(7,-k1+q3))*
 vrtx(sbar(-2,-q1),s(1,q1+q4),photon(-8,-q4))*
 vrtx(sbar(6,k1+q2),s(-4,-q2),g(3,-k1))*
 vrtx(sbar(-6,-q3),s(7,-k1+q3),g(4,k1))*
 vrtx(sbar(2,-q1-q4),s(5,-k1-q2),sbar(8,k1-q3),b(-1,p1));
 
Local D39OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,-k1+q1))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(-2,-q1),s(7,-k1+q1),g(4,k1))*
 vrtx(sbar(-6,-q3),s(1,-q2-q4),sbar(8,k1-q1),b(5,-k1+p1));
 
Local D40OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,-k1+q3))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(-6,-q3),s(7,-k1+q3),g(4,k1))*
 vrtx(sbar(-2,-q1),s(1,-q2-q4),sbar(8,k1-q3),b(5,-k1+p1));
 
Local D41OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,-q2-q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(s(7,-k1+q3))*
 vrtx(sbar(2,q2+q4),s(-4,-q2),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(sbar(-6,-q3),s(7,-k1+q3),g(4,k1))*
 vrtx(sbar(6,-k1-q1),s(1,-q2-q4),sbar(8,k1-q3),b(-1,p1));
 
Local D42OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,-k1+q1))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(-2,-q1),s(7,-k1+q1),g(4,k1))*
 vrtx(sbar(2,-q3-q4),s(-4,-q2),sbar(8,k1-q1),b(5,-k1+p1));
 
Local D43OneLoop= (+1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(g(3,-k1))*
 prop(b(5,-k1+p1))*
 prop(s(7,k1-q2))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(bbar(6,k1-p1),b(-1,p1),g(3,-k1))*
 vrtx(sbar(8,-k1+q2),s(-4,-q2),g(4,k1))*
 vrtx(sbar(-2,-q1),s(7,k1-q2),sbar(2,-q3-q4),b(5,-k1+p1));
 
Local D44OneLoop= (-1)*
 pol(b(-1,p1))*
 pol(s(-2,q1))*
 pol(sbar(-4,q2))*
 pol(s(-6,q3))*
 pol(photon(-8,q4))*
 prop(s(1,q3+q4))*
 prop(g(3,-k1))*
 prop(s(5,k1+q1))*
 prop(s(7,k1-q2))*
 vrtx(sbar(-6,-q3),s(1,q3+q4),photon(-8,-q4))*
 vrtx(sbar(-2,-q1),s(5,k1+q1),g(3,-k1))*
 vrtx(sbar(8,-k1+q2),s(-4,-q2),g(4,k1))*
 vrtx(sbar(2,-q3-q4),s(7,k1-q2),sbar(6,-k1-q1),b(-1,p1));

* end

